env:
BUILDKITE_BUILD_PATH: "/home/cloud_user/"
  
steps:
  - input: "Select Environment"
    fields:
      - select: "Env"
        key: "TEST_ENV"
        options:
          - label: "DevInt"
            value: "DevInt"
          - label: "PreProd"
            value: "PreProd"
  - wait
  - label: ":salesforce: run tests $TEST_ENV"
    command: "test.sh"
