steps:
  - input: "Select Environment"
    fields:
      - select: "Env"
        key: "TEST_ENV"
        options:
          - label: "Dev"
            value: "Dev"
          - label: "QA"
            value: "QA"
  - wait
  - label: ":salesforce: run tests $TEST_ENV"
    command: "test.sh"
