steps:
  - input: "Select Environment"
    fields:
      - select: "Env"
        key: "TEST_ENV"
        options:
          - label: "DevInt"
            value: "DevInt"
          - label: "PreProd"
            value: "PreProd"
  - wait          
  - command: "test.sh"
